### PR TITLE
Bug fix in forward and bi-directional lstm in handling bias

### PR DESCRIPTION
**Pull request by sonu1-p**
The converter was not setting the value of R bias correctly during
onnx conversion.

We simply set the R biases to zero since the current conversion code
is already setting W bias to the Keras' bias value. We expect the sum
of the biases Wb + Rb to be the same as Keras' bias since Keras uses
a single bias combining both.

Changes to be committed:

	modified:   keras2onnx/ke2onnx/bidirectional.py
	modified:   keras2onnx/ke2onnx/lstm.py
	modified:   tests/test_layers.py

### CODE REVIEW

**Comment by jiafatom** [comment]
@sonu1-p  can you please sign CLA? thanks

**Comment by sonu1-p** [comment]
Hi David, I have signed it, don't know why this page is not reflecting the same.

**Comment by sonu1-p** [comment]
When I click on license/cla details, it says - You have signed the CLA for onnx/keras-onnx

**Comment by sonu1-p** [comment]
Seems like it is reflected now. Thanks!

**Comment by jiafatom** [comment]
LGTM, thank you very much for the change!

**Pull request merged**
