### PR TITLE
Fix cli

### PR DESCRIPTION
**Pull request by yan12125**
Fixes the following error for `keras2onnx.cli`:
```
$ python -m keras2onnx.cli model.h5 model.onnx
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.summary API due to missing TensorBoard installation.
2020-10-04 21:22:14.120564: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-10-04 21:22:14.140245: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 3393800000 Hz
2020-10-04 21:22:14.140520: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55af0d6ee810 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-10-04 21:22:14.140537: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-10-04 21:22:14.140653: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.8/site-packages/keras2onnx/cli.py", line 36, in <module>
    fire.Fire(main)
  File "/usr/lib/python3.8/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/lib/python3.8/site-packages/fire/core.py", line 463, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/lib/python3.8/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/usr/lib/python3.8/site-packages/keras2onnx/cli.py", line 28, in main
    oxml = convert_keras(kml, kml.model, '', opset, channel_first)
AttributeError: 'Sequential' object has no attribute 'model'
```

Test environment: Arch Linux, TensorFlow 2.3.1, Python 3.8.5

### CODE REVIEW

**Comment by yan12125** [comment]
Looks like the test failure with Python 3.6 is that an older ONNX is used. From https://dev.azure.com/onnxmltools/59aa92dc-e81c-44cb-8e34-54cbb6dcd732/_apis/build/builds/15632/logs/26,
```
2020-10-05T02:08:37.6641499Z Requirement already satisfied: onnx in /home/vsts/.conda/envs/py3.6/lib/python3.6/site-packages (from keras2onnx==1.7.1) (1.5.0)
```


```
2020-10-05T02:09:52.9196788Z On converting a model with opset < 11, the masking layer result may be incorrect if the model input is in range (0, 1.0).
2020-10-05T02:09:52.9197606Z The ONNX operator number change on the optimization: 20 -> 16
2020-10-05T02:09:52.9198197Z On converting a model with opset < 11, the masking layer result may be incorrect if the model input is in range (0, 1.0).
2020-10-05T02:09:52.9198960Z The ONNX operator number change on the optimization: 20 -> 16
2020-10-05T02:09:52.9199794Z case = sequential, result mismatch for expected = -0.00091168255, actual = -0.00091952085 at location 14
2020-10-05T02:09:52.9200422Z case = sequential, 1 mismatches out of 16 for list 0
```

Opset 11 is in ONNX 1.6 (https://github.com/onnx/onnx/releases/tag/v1.6.0), thus the failure.

**Comment by jiafatom** [comment]
Thanks for the contribution. This test failure is some random number issue which is fine. Can you do some dummy change and resubmit the code (rerun the test)? thanks.

**Comment by yan12125** [comment]
Thanks for the suggestion! I amended the git commit and force pushed.

**Review by jiafatom — APPROVED** [review]
Thanks for your contribution!

**Pull request merged**
